services:
  - type: web
    name: roadmap-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    rootDir: backend
    plan: starter
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 # render ডিফল্ট পোর্ট (নিচে explain করব)

  - type: static
    name: roadmap-frontend
    env: static
    buildCommand: npm install && npm run build
    rootDir: frontend/roadmap-app
    publishDir: frontend/roadmap-app/dist
    plan: starter
    autoDeploy: true
