services:
  - type: web
    name: roadmap-app-backend
    env: node
    plan: free
    region: oregon
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm run start
    rootDirectory: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 22.15.0

  - type: web
    name: roadmap-app-frontend
    env: static
    plan: free
    region: oregon
    buildCommand: cd frontend/roadmap-app && npm install && npm run build
    staticPublishPath: frontend/roadmap-app/dist
    rootDirectory: frontend/roadmap-app
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 22.15.0