services:
  - type: web
    name: roadmap-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000

  - type: static
    name: roadmap-frontend
    env: static
    rootDir: frontend/roadmap-app
    buildCommand: npm install && npm run build
    publishDir: dist
    autoDeploy: true
